name = "warp-generator"
main = "_worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "WARP_KV", id = "403f8a13d95f47d1af9b1192a5c5a31a" }
]
